@startuml
left to right direction
package GérerCompte{
    :artisant : as a
    :BDD : as b << Application >>
    usecase "Creer un compte" as UC1
    usecase "Modifier compte" as UC2
    usecase "Ajouter informations de son entreprise " as UC3
    a -- UC1
    UC1 -- b
    a -- UC2
    UC2 -- b
    a -- UC3
    UC3 -- b
}

package GénérerFacture{
    :artisant : as r
    :BDD : as d << Application >>
    usecase "Creet une facture" as UC4
    usecase "Modifier une facture" as UC5
    usecase "Supprimer une facture" as UC6
    r -- UC4
    UC4 -- d
    r -- UC5
    UC5 -- d
    r -- UC6
    UC6 -- d
}
package GénererDevis{
    :artisant : as t
    :BDD : as dd << Application >>
    usecase "Creer un devis" as UC7
    usecase "Modifier un devis" as UC8
    usecase "Supprimer un devis" as UC9
    t -- UC7
    UC7 -- dd
    t -- UC8
    UC8 -- dd
    t -- UC9
    UC9 -- dd
}
GénererDevis .>  GénérerFacture
package GérerClient{
    :artisant : as s
    :BDD : as B << Application >>
    usecase "Ajouter un client" as UC10
    usecase "Modifier un client" as UC11
    usecase "Supprimer un client" as UC12
    s -- UC10
    UC10 -- B
    s -- UC11
    UC11 -- B 
    s -- UC12
    UC12 -- B
}
@enduml