@startuml
left to right direction
:artisant: as a
:BDD: as b << Application >>
package ServicesArtisant {
    usecase "creer propre compte" as UC1
    usecase "gérer les cliets" as UC2
    usecase "gestion d'evis" as UC3
    usecase "affectuer un factore" as UC4
    usecase "consulter les parametres" as UC5
    (UC3).>(UC4) : include
}
a -- UC1
a -- UC2
a -- UC3
a -- UC4
a -- UC5

UC2 -- b
UC3 -- b
UC4 -- b
@enduml
